[project]
name = "speach-to-text"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.11.0",
    "ffmpeg>=1.4",
    "flake8>=7.3.0",
    "flask>=3.1.2",
    "openai-whisper>=20250625",
    "pandas>=2.3.3",
    "pytest==8.4.2",
    "ruff>=0.14.6",
    "torch>=2.9.1",
]

# Add the PyTorch CPU index as an additional index
[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
#recommend the use of explicit = true to ensure that the index is only used for torch
explicit = true

# Tell uv that ONLY torch should come from this index ->  To point torch to the desired index:
[tool.uv.sources]
torch = [
    { index = "pytorch-cpu" }
]
