# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI Pipeline

on:
  push:
    branches: [ "main", "dev", "test"]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  build:
    name: Run Pytest and formating
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Install uv
        run: pip install uv

      - name: Install project dependencies
        run: uv sync 

      - name: Install additional packages
        run: uv add flake8
          #if not [ -f pyproject.toml ] or [ -f uv.lock ]  ; then pip install -r requirements.txt; fi
      
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
      - name: Run pytest
        run: |
          PYTHONPATH=. pytest --maxfail=1 --disable-warnings -q
      - name: Lint with ruff
        run: ruff check --output-format=github . --exclude tests
      - name: Check formatting with black
        run: black --check .